# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: SSISBuild@1
  inputs:
    projectPath: 'C:\Users\flemming.andersen\source\repos\ISSFINALTEST'
    stripSensitive: false
    outputPath: '$(Build.ArtifactStagingDirectory)'


- task: SSISDeploy@1
  inputs:
    sourcePath: 'C:\Users\flemming.andersen\source\repos\ISSFINALTEST'
    destinationType: 'ssisdb'
    destinationServer: 'localhost'
    destinationPath: '/SSISDB/ISS Test/ISSTest2'
    authType: 'win'
    whetherOverwrite: 'yes'
    whetherContinue: 'no'
